# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kish < Formula
  desc "kish client"
  homepage ""
  version "0.0.14"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/no2a/kish/releases/download/v0.0.14/kish_0.0.14_darwin_arm64.tar.gz"
      sha256 "c481e093b88dd3ab23f5dff7c3fa4680e5645ed9db57ccdd8edf216940c9526f"

      def install
        bin.install "kish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/no2a/kish/releases/download/v0.0.14/kish_0.0.14_darwin_amd64.tar.gz"
      sha256 "993d038c62ca3fc75e16aa1c4005e301fc27d1224640ba074e536aacd0a5fb60"

      def install
        bin.install "kish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/no2a/kish/releases/download/v0.0.14/kish_0.0.14_linux_amd64.tar.gz"
      sha256 "3c599f7e0799f65a953c9a0e3a7571a1cbbb408b1e21c2ced4b3188048a0000c"

      def install
        bin.install "kish"
      end
    end
  end
end
