# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kish < Formula
  desc "kish client"
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/no2a/kish/releases/download/v0.0.3/kish_0.0.3_darwin_arm64.tar.gz"
      sha256 "3dd61471f4e7ff64e3be2b1ff2426e5d0ad5d0d52136f4bc16470da751919ad9"

      def install
        bin.install "kish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/no2a/kish/releases/download/v0.0.3/kish_0.0.3_darwin_amd64.tar.gz"
      sha256 "3c844bacee14cab9d2874314701661487f1405b44ff137e07718ae9720c487b3"

      def install
        bin.install "kish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/no2a/kish/releases/download/v0.0.3/kish_0.0.3_linux_amd64.tar.gz"
      sha256 "74033781456ce25074bc7b5e5a138be8887efd8156fda040c9fb7d21ffaf52ce"

      def install
        bin.install "kish"
      end
    end
  end
end
